# Varx Tools Configuration
# all directories are relative to the lib folder

[[package]]
name = "varx_themes"
path = "varx_themes.exe"
keyword = "themes"
description = "Theme manager for Varx"

[[package]]
name = "neovim"
path = "bin/nvim.exe"
keyword = "nvim"
description = "Highly extensible text editor"

[[package]]
name = "fastfetch"
path = "fastfetch.exe"
keyword = "fastfetch"
description = "A fast system information tool"

[[package]]
name = "alacritty"
path = "alacritty.exe"
keyword = "alacritty"
description = "A fast, cross-platform, OpenGL terminal emulator"
